// Milesight Open API — wire types.
//
// PROVENANCE. Every shape here was checked against Milesight's published
// Development Platform docs on 2026-08-03 (CLAUDE.md: never contradict §4 from
// memory; [VERIFY] items get checked, never guessed). Source pages are cited
// per block. Where the docs are silent this file says so instead of inventing
// a field.
//
// Path template is `/{serviceName}/openapi/{version}/**`; `device` is the only
// service name that appears in the published list. `/oauth/token` is the one
// endpoint with no prefix and no version.
//   https://www.milesight.com/development-platform/docs/en/api-reference/request-structure.html

/** Envelope on every success (HTTP 200). Payload is nested under `data`. */
export interface MdpSuccess<T> {
  data: T;
  status: 'Success';
  requestId: string;
}

/**
 * Envelope on 4xx/5xx. `errCode` is a string slug ("authentication_failed"),
 * not a number; Milesight publishes no comprehensive code table.
 *   https://www.milesight.com/development-platform/docs/en/api-reference/response-results.html
 */
export interface MdpFailure {
  status: 'Failed';
  requestId?: string;
  errCode?: string;
  errMsg?: string;
}

/**
 * POST /oauth/token — OAuth 2.0 client credentials, body form-encoded.
 * Access token lives ~1 h, refresh token 30 days. No `token_type` is returned.
 *   https://www.milesight.com/development-platform/docs/en/api-reference/get-an-access-token.html
 */
export interface MdpTokenData {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  refresh_token_expires_in: number;
}

/**
 * POST /device/openapi/v1/devices — the ENTIRE documented request body.
 *
 * Four fields. There is no separate `devEUI`, no model or device-profile
 * field, no application id (it comes from the bearer token's Application), and
 * no joinType/appKey/appEUI. MDP is not a ChirpStack-style LNS API: Milesight
 * resolves the model and the LoRaWAN keys from the SN/EUI itself.
 *   https://www.milesight.com/development-platform/docs/en/api-reference/add-a-device.html
 */
export interface MdpAddDeviceRequest {
  /** The SN **or** the EUI. We send the upper-cased DevEUI. */
  snDevEUI: string;
  name: string;
  description?: string;
  /** Max 20 entries. */
  tag?: string[];
}

export interface MdpAddDeviceResponse {
  sn: string;
  deviceId: string;
}

/**
 * GET /device/openapi/v1/devices/{deviceId}. Only the fields the console
 * actually reads are typed; the response carries more.
 *   https://www.milesight.com/development-platform/docs/en/api-reference/
 */
export interface MdpDevice {
  deviceId: string;
  sn?: string;
  devEUI?: string;
  name?: string;
  model?: string;
  deviceType?: string;
  connectStatus?: string;
  electricity?: number;
  firmwareVersion?: string;
  lastUpdateTime?: string;
  /** The only documented way to read an Application id back out of MDP. */
  application?: { applicationId?: string; applicationName?: string };
}

/** POST /device/openapi/v1/devices/search — POST, not GET. */
export interface MdpDeviceSearchRequest {
  pageSize: number;
  pageNumber: number;
  sn?: string;
  devEUI?: string;
  name?: string;
  model?: string;
  connectStatus?: string;
  tag?: string[];
}

export interface MdpPage<T> {
  pageSize: number;
  pageNumber: number;
  total: number;
  content: T[];
}

/**
 * Operations Milesight does NOT expose over the public API. Verified against
 * the complete published interface list (16 endpoints: 2 auth, 10 device, 3
 * RPS, 1 task) — these are console-only, so the console records the result of
 * a human doing them rather than pretending to automate them.
 */
export type MdpConsoleOnlyOperation =
  | 'createGroup'
  | 'createApplication'
  | 'listApplications'
  | 'registerWebhookCallback'
  | 'rotateWebhookSecret';

export const CONSOLE_ONLY_STEPS: Readonly<Record<MdpConsoleOnlyOperation, string>> = {
  createGroup: 'MDP console → Groups → Add. Creating the Group generates the Application.',
  createApplication: 'Applications are generated by creating a Group; there is no separate step.',
  listApplications: 'MDP console → Applications. Copy the id into this farm.',
  registerWebhookCallback:
    'MDP console → Application → Application Settings → Webhook → Callback URI → Add, then Test.',
  rotateWebhookSecret:
    'MDP console → Application → Application Settings → Webhook. Re-add the callback and copy the new signing material.',
};
