-- partition-rls-audit.sql — MOVED. This file no longer contains any DDL.
--
-- `public.partition_rls_audit()` — the read-only catalog bridge that
-- `partitions.ts` / `rls.test.ts` call to hold every partition to its parent's
-- row security — now lives in a numbered migration:
--
--     packages/db/migrations/0023_partition_hardening.sql   (PART 2)
--
-- It used to live here because packages/db/migrations was owned by another
-- agent when it was written, so it was applied out-of-band with execute_sql and
-- parked beside the tests. That meant a database rebuilt from migrations came
-- up without it, and the RLS suite failed with AUDIT_RPC_MISSING — the suite
-- that exists because a hand-maintained partition list missed a month and
-- leaked 1,050 rows across tenants.
--
-- The function's security properties are unchanged in 0023: catalog metadata
-- only (never a table row), SECURITY DEFINER with `search_path` pinned to
-- `pg_catalog, public`, `stable`, no dynamic SQL, and EXECUTE revoked from
-- public / anon / authenticated and granted to `service_role` alone —
-- `service_role` bypasses RLS by definition, so it gains nothing it could not
-- already see.
--
-- This stub is kept rather than deleted only because
-- `packages/db/migrations/0015_staff_isolation.sql` cites this path when it
-- borrows the same safety argument for `app.staff_policy_audit()`. Do not put
-- DDL back in it. Anything the audit function needs belongs in a migration.
